os: linux
dist: jammy
language: generic
# Test this with multiple versions of R.
# rocker/verse:4.3 is the oldest version for which testthat >= 3.2.0, with local_mocked_bindings, is easily available.
env:
- ROCKER_VERSION=4.4
- ROCKER_VERSION=4.3
services:
  - docker
before_install:
- docker pull rocker/verse:${ROCKER_VERSION}
script:
- docker run -v $PWD/:/civis-r rocker/verse:${ROCKER_VERSION} /bin/bash -c "cd /civis-r && Rscript tools/install-and-run-tests.R"
