os: linux
dist: jammy
language: generic
# Test this recent and not so recent versions of R.
env:
- ROCKER_VERSION=4.4
- ROCKER_VERSION=4.0
services:
  - docker
before_install:
- docker pull rocker/verse:${ROCKER_VERSION}
script:
- docker run -v $PWD/:/civis-r rocker/verse:${ROCKER_VERSION} /bin/bash -c "cd /civis-r && Rscript tools/install-and-run-tests.R"
